#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jun 16 15:24:27 2019

@author: eric
"""




current_savings = 0.0
months = 0
r = .04
semi_annual = .07
total_cost = 1000000
x = 0
low = 0
high = 1
guess = (high + low)/2.0
num_guesses = 0

annual_salary = input("Starting annual salary: ")
annual_salary = float(annual_salary)

portion_down_payment = .25 *total_cost
monthly_salary = annual_salary/12
monthly_salary_saved = monthly_salary*guess

for x in range(0,36):   
    months = months + 1
    if(months%6 == 0):
        monthly_salary_saved = monthly_salary_saved*semi_annual + monthly_salary_saved        
    current_savings = monthly_salary_saved + current_savings*(r/12) + current_savings

while abs(current_savings - portion_down_payment) > 100:  
    
    if(current_savings < portion_down_payment):
        low = guess
    else:
        high = guess
        
    guess = (high + low)/2.0
    num_guesses += 1
    current_savings = 0
    months = 0
    monthly_salary = annual_salary/12
    monthly_salary_saved = monthly_salary*guess
    
    for x in range(0,36):
        months = months + 1
        if(months%6 == 0):
            monthly_salary_saved = monthly_salary_saved*semi_annual + monthly_salary_saved        
        current_savings = monthly_salary_saved + current_savings*(r/12) + current_savings
           
print(guess)
